# Generated by Django 6.0.4 on 2026-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin_annee', models.DateField(blank=True, null=True)),
                ('acces_bloques', models.BooleanField(default=False)),
            ],
        ),
    ]
