# Generated by Django 6.0.4 on 2026-05-21 10:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lycee', models.CharField(blank=True, max_length=200)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='courses.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annees', models.ManyToManyField(related_name='specialites', to='courses.annee')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_pack', models.CharField(choices=[('annuel', 'Pack annuel'), ('semestriel', 'Pack semestriel'), ('trimestriel', 'Pack trimestriel'), ('chapitre', 'Pack chapitre'), ('exercices', 'Pack exercices'), ('bac', "Pack résolution d'épreuves")], default='annuel', max_length=20)),
                ('est_visible', models.BooleanField(default=True)),
                ('est_populaire', models.BooleanField(default=False)),
                ('est_nouveau', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.annee')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.matiere')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='courses.specialite')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='specialites',
            field=models.ManyToManyField(related_name='matieres', to='courses.specialite'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_video', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice corrigé'), ('bac', "Correction d'épreuve")], default='cours', max_length=20)),
                ('duree', models.CharField(blank=True, max_length=20)),
                ('url_hebergement', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('cloudinary_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.enseignant')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PackVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0)),
                ('est_video_explicative', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.pack')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('pack', 'video')},
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='videos',
            field=models.ManyToManyField(related_name='packs', through='courses.PackVideo', to='courses.video'),
        ),
    ]
