# Generated by Django 6.0.4 on 2026-05-18 15:29

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_video_fichier_video_alter_pack_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fichier_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
